config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  resources :users do
   resources :addresses
  end
end

app/models/address.rb
# == Schema Information
#
# Table name: addresses
#
#  id         :integer          not null, primary key
#  street     :string
#  country    :string
#  city       :string
#  state      :string
#  zip_code   :integer
#  latitude   :float
#  longitude  :float
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Address < ApplicationRecord
  geocoded_by :full_address
  before_save :geocode
  validates :city,
            :state,
            :street,
            :user_id,
            :zip_code,
            presence: true

  belongs_to :user

  def full_address
    [city, state, street, zip_code].compact.join(', ')
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  first_name             :string
#  last_name              :string
#  phone_number           :string
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name,
            :last_name,
            :phone_number,
            :avatar,
            presence: true

  has_one_attached :avatar
  has_many :addresses
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :find_user

  def index
    @addresses = @user.addresses
  end

  def new
    @address = Address.new
  end

  def show
    @address = Address.find params[:id]
  end

  def create
    if Address.create(address_params.merge(user_id: @user.id))
      flash[:success] = "Place added!"
      redirect_to user_path(@user)
    else
      redirect_to :back
    end
  end

  private

  def find_user
    @user = User.find params[:user_id]
  end

  def address_params
    params.require(:address).permit(:city,
                                    :country,
                                    :state,
                                    :street,
                                    :zip_code)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_sign_up_permitted_parameters, if: :devise_controller?
  before_action :configure_update_permitted_parameters, if: :devise_controller?

  protected

  def configure_sign_up_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :first_name, :last_name, :phone_number, :avatar ])
  end

  def configure_update_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [ :first_name, :last_name, :phone_number, :avatar ])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :validate_current_user

  def index
    @users = User.all
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to :root
    else
      render :edit
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  private

  def validate_current_user
    redirect_to root_path unless current_user.id == params[:id].to_i
  end

  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :phone_number,
      :avatar,
      addresses_attributes: [:id, :street, :city, :state, :country, :zip_code]
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/addresses/_address.html.erb
<ul>
  <li>
    <%= address.country %>
  </li>
  <li>
    <%= address.state %>
  </li>
  <li>
    <%= address.city%>
  </li>
  <li>
    <%= address.street%>
  </li>
  <li>
    <%= address.zip_code%>
  </li>
  <li>
    <%= address.latitude%>
  </li>
  <li>
    <%= address.longitude%>
  </li>
</ul>

app/views/addresses/_form.html.erb
<h2>Add your address here --- is this always visible?</h2>

<%= form_for @address, url: user_addresses_path(@user) do |f| %>
  <% if @address.errors.any? %>
    <h2>
    <div id="error_explanation">
      <%= pluralize(@address.errors.count, "error") %>
      prohibited this article from being saved:
    </h2>
    <ul>
      <% @address.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <%end%>
    </ul>
    </div>
  <%end%>

  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>

  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <%= f.label :street %><br />
    <%= f.text_field :street %>
  </div>

  <div class="field">
    <%= f.label :zip_code %><br />
    <%= f.text_field :zip_code %>
  </div>

  <div class="actions">
    <%= f.submit "Add your Address"%>
  </div>

<% end %>

<%= link_to "Back to home", :root %>

app/views/addresses/index.html.erb
<h1>This is the index-page</h1>
<%= link_to "Add New Addresses", new_user_address_path(@user) %></br>
<%= link_to "Show Profile", user_path(current_user.id) %>
<%= render partial: "address", collection: @addresses %>

app/views/addresses/new.html.erb
<h1>This is the new-page</h1>
<div>
  <%= render 'form' %>
</div>

app/views/addresses/show.html.erb
<header><h1>This is the show-page</h1></header>

<%= link_to 'Add place', new_address_path %>

<div>
  <ul>
    <%= render @address %>
  </ul>
</div>

<%= link_to "Back", :back %>

app/views/home/index.html.erb
<%= link_to "Sign Out", destroy_user_session_path, method: :delete %>

<h1> Welcome <%= current_user.first_name%> </h1>
<% if current_user.avatar.attached? %>
  <%= image_tag current_user.avatar.variant(resize:"200x200") %>
<%end%>

<br>

<%= link_to "Show Profile", user_path(current_user.id) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetAlert</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Edit your profile</h1>

<%= form_for @user, url: user_path(@user), html: { method: :put } do |f| %>
  <div class="field">
    <%= f.label :first_name%><br />
    <%= f.text_field :first_name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :last_name%><br />
    <%= f.text_field :last_name, autofocus: false %>
  </div>

  <div class="field">
    <%= f.label :phone_number %><br />
    <%= f.text_field :phone_number %>
  </div>

  <div class="field">
    <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
    <%= f.password_field :password, autocomplete: "off" %>
    <% if @minimum_password_length %>
      <br />
      <em><%= @minimum_password_length %> characters minimum</em>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
    <%= f.password_field :current_password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :avatar %><br />
    <%= f.file_field :avatar %>
  </div>

  <% if @user.avatar.attached? %>
    <%= image_tag @user.avatar.variant(resize:"200x200") %>
  <%end%>

  <div class="actions">
    <%= f.submit "Update" %>
    <%= link_to "Cancel", user_path(current_user) %>
  </div>
<% end %>

app/views/users/index.html.erb
<%= link_to "Sign Out", destroy_user_session_path, method: :delete %>

<h1>This is the Index-Page for Users</h1>

<ul>
  <%- @users.each do |u| %>
    <li>
      <%= u.first_name %>
      <%= u.last_name %>
    </li>
  <% end %>
</ul>

<%= link_to "Edit Profile", edit_user_path(current_user.id) %>
<%= link_to "Back to home", :root %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<%= link_to "Sign Out", destroy_user_session_path, method: :delete %>

<h1>This is the Show-Page for User</h1>
<%= current_user.first_name %>
</br>

<%= link_to "Edit Profile", edit_user_path(current_user) %>
<%= link_to "Manage Address", user_addresses_path(current_user) %></br>
<%= link_to "Back to home", :root %>